---
# reliabot: mapping=4 offset=2 sequence=4
# reliabot: keep=. # this is mostly for test coverage (as is ./ in next)
# reliabot: ignore=./reliabot # already tracked in repository root
# reliabot: ignore=testdir/
version: 2
updates:
  - directory: /
    package-ecosystem: pip
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
    groups:
      gh-actions-infrastructure:
        patterns:
          - actions/*
          - github/codeql-action/*
          - ossf/*
          - step-security/*
      gh-actions-releases:
        patterns:
          - ncipollo/release-action
          - orhun/git-cliff-action
          - pypa/*
  - directory: /fuzz
    package-ecosystem: docker
    schedule:
      interval: monthly
